package com.dev.nigrani.alerts;

import com.dev.nigrani.alerts.dtos.AlertResponse;
import com.dev.nigrani.alerts.dtos.CreateAlertRequest;
import com.dev.nigrani.alerts.dtos.SummaryAlertResponse;
import com.dev.nigrani.alerts.models.Alert;
import com.dev.nigrani.alerts.models.AlertSeverity;
import com.dev.nigrani.alerts.models.AlertSource;
import com.dev.nigrani.alerts.models.AlertStatus;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;

@Service
@RequiredArgsConstructor
@Transactional
public class AlertServiceImpl implements AlertService {

    private final AlertRepository alertRepository;

    @Override
    @Transactional(readOnly = true)
    public List<AlertResponse> getAlerts(AlertSeverity severity) {

        List<Alert> alerts = alertRepository.findAll();

        if (severity != null) {
            alerts = alerts.stream()
                    .filter(alert -> alert.getSeverity() == severity)
                    .toList();
        }

        return alerts.stream()
                .map(this::toResponse)
                .toList();
    }

    @Override
    @Transactional(readOnly = true)
    public AlertResponse getAlertById(Long alertId) {

        Alert alert = alertRepository.findById(alertId)
                .orElseThrow(() ->
                        new IllegalArgumentException(
                                "Alert not found: " + alertId
                        )
                );

        return toResponse(alert);
    }

    @Override
    public SummaryAlertResponse getAlertSummary() {

        long totalAlerts = alertRepository.count();
        long criticalAlerts =
                alertRepository.countBySeverity(AlertSeverity.CRITICAL);
        long warningAlerts =
                alertRepository.countBySeverity(AlertSeverity.WARNING);

        return new SummaryAlertResponse(
                totalAlerts,
                criticalAlerts,
                warningAlerts
        );
    }

    @Override
    public AlertResponse createAlert(CreateAlertRequest request) {

        if (request == null) {
            throw new IllegalArgumentException(
                    "Alert request cannot be null"
            );
        }

        Alert alert = Alert.builder()
                .title(request.getTitle())
                .description(request.getDescription())
                .instituteId(request.getInstituteId())
                .instituteName(request.getInstituteName())
                .location(request.getLocation())
                .type(request.getType())
                .severity(request.getSeverity())
                .confidenceScore(request.getConfidenceScore())

                // Defaults generated by backend
                .riskScore(calculateRiskScore(request.getSeverity()))
                .status(AlertStatus.OPEN)
                .source(AlertSource.RULE_ENGINE)

                .evidenceReference(request.getEvidenceReference())
                .reportedValue(request.getReportedValue())
                .detectedValue(request.getDetectedValue())
                .variance(request.getVariance())
                .detectedAt(
                        request.getDetectedAt() != null
                                ? request.getDetectedAt()
                                : LocalDateTime.now()
                )
                .build();

        Alert savedAlert = alertRepository.save(alert);

        return toResponse(savedAlert);
    }

    private int calculateRiskScore(AlertSeverity severity) {

        if (severity == AlertSeverity.CRITICAL) {
            return 100;
        }

        if (severity == AlertSeverity.WARNING) {
            return 50;
        }

        return 0;
    }

    private AlertResponse toResponse(Alert alert) {

        return AlertResponse.builder()
                .id(alert.getId())
                .title(alert.getTitle())
                .description(alert.getDescription())
                .instituteId(alert.getInstituteId())
                .instituteName(alert.getInstituteName())
                .location(alert.getLocation())
                .type(alert.getType())
                .severity(alert.getSeverity())
                .confidenceScore(alert.getConfidenceScore())
                .riskScore(alert.getRiskScore())
                .status(alert.getStatus())
                .evidenceReference(alert.getEvidenceReference())
                .reportedValue(alert.getReportedValue())
                .detectedValue(alert.getDetectedValue())
                .variance(alert.getVariance())
                .detectedAt(alert.getDetectedAt())
                .build();
    }
}