package com.dev.nigrani.alerts.models;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.time.LocalDateTime;

    @Entity
    @Table(name = "alerts")/*table name is alerts*/
    @Getter
    @Setter
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public class Alert {

        /** Primary key generated by PostgreSQL when a new alert is saved. */
        @Id
        @GeneratedValue(strategy = GenerationType.IDENTITY)
        private Long id;

        /** Short heading shown at the top of the alert card. */
        @Column(nullable = false, length = 150)
        private String title;

        /** Full explanation shown below the institute location. */
        @Column(nullable = false, length = 1000)
        private String description;

        /**
         * The institute identifier. This remains a simple ID for now because the
         * Institute entity belongs to the other developer's module.
         */
        @Column(nullable = false)
        private Long instituteId;

        /** Institute name saved for fast, simple display in the alert card. */
        @Column(nullable = false, length = 200)
        private String instituteName;

        /** Human-readable location shown by the Android UI. */
        @Column(nullable = false, length = 200)
        private String location;

        /** What kind of anomaly was found. Stored as readable text, not a number. */
        @Enumerated(EnumType.STRING)
        @Column(nullable = false, length = 40)
        private AlertType type;

        /** CRITICAL or WARNING, used by the filter chips and dashboard counts. */
        @Enumerated(EnumType.STRING)
        @Column(nullable = false, length = 20)
        private AlertSeverity severity;

        /** Rule/AI confidence from 0 to 100. The API will later format it as "96%". */
        @Column(nullable = false)
        private Integer confidenceScore;

        /** Priority score from 0 to 100, reserved for the later risk/assignment module. */
        @Column(nullable = false)
        private Integer riskScore;

        /** Current operational state of the alert. */
        @Enumerated(EnumType.STRING)
        @Column(nullable = false, length = 30)
        private AlertStatus status;

        /** Whether the MVP rule engine or a staff member created this alert. */
        @Enumerated(EnumType.STRING)
        @Column(nullable = false, length = 20)
        private AlertSource source;

        /** Optional permanent URL/object key/record ID used by the View Evidence button. */
        @Column(length = 500)
        private String evidenceReference;

        /** Optional values for the Dashboard attendance-anomaly card. */
        private Integer reportedValue;

        private Integer detectedValue;

        private Integer variance;

        /** The moment the monitoring rule detected the problem. */
        @Column(nullable = false, updatable = false)
        private LocalDateTime detectedAt;

        /** Audit timestamp: automatically set once before the row is first saved. */
        @Column(nullable = false, updatable = false)
        private LocalDateTime createdAt;

        /** Audit timestamp: automatically refreshed whenever the row is updated. */
        @Column(nullable = false)
        private LocalDateTime updatedAt;

        /** Sets timestamps that must exist before a new Alert is inserted. */
        @PrePersist
        private void setCreationTimestamps() {
            LocalDateTime now = LocalDateTime.now();
            if (detectedAt == null) {
                detectedAt = now;
            }
            createdAt = now;
            updatedAt = now;
        }

        /** Refreshes only the update timestamp before an existing Alert is changed. */
        @PreUpdate
        private void setUpdateTimestamp() {
            updatedAt = LocalDateTime.now();
        }
    }

